[main]
job_complete_timeout: 60
show_cursor: False
default_printer: Voron
use_default_menu: True

[printer Voron]
moonraker_host: 127.0.0.1
moonraker_port: 7125
moonraker_api_key: False

[printer Ender 3 Max]
moonraker_host: 127.0.0.1
moonraker_port: 7126
moonraker_api_key: False

[printer SP5]
moonraker_host: 10.0.0.9
moonraker_port: 7125
moonraker_api_key: False

[preheat Nozzle 220]
bed: 0
extruder: 220

[preheat Filament 0]
bed: 0
extruder: 0

[preheat Bed 110]
bed: 110
extruder: 0

[menu __main lights]
icon: light
name: Lights

[menu __main lights caselightson]
name: Lights on
icon: increase
method: printer.gcode.script
params: {"script":"CASELIGHTS_ON"}

[menu __main lights caselightsoff]
name: Lights off
icon: decrease
method: printer.gcode.script
params: {"script":"CASELIGHTS_OFF"}

[menu __main actions maintenance]
name: Maintenance
icon: toolchanger

[menu __main actions maintenance clean]
name: Clean Nozzle
icon: extruder
method: printer.gcode.script
params: {"script":"clean_nozzle"}

[menu __main actions maintenance sync]
name: Sync Configs
icon: files
method: printer.gcode.script
params: {"script":"BACKUP_CONFIG"}

#~# --- Do not edit below this line. This section is auto generated --- #~#

#~#
#~# [main]
#~# theme = voron
#~# font_size = large
#~# confirm_estop = True
#~#
