
/* DO NOT EDIT! This is an autogenerated file. See scripts/buildcommands.py. */

#include <stdint.h>
#include "board/irq.h"
#include "board/pgm.h"
#include "compiler.h"
#include "initial_pins.h"

void
ctr_run_initfuncs(void)
{
    extern void initial_pins_setup(void);
    initial_pins_setup();
    extern void usb_init(void);
    usb_init();
    extern void chipid_init(void);
    chipid_init();
}

void
ctr_run_taskfuncs(void)
{
    irq_poll();
    extern void complete_task(void);
    complete_task();
    irq_poll();
    extern void usb_ep0_task(void);
    usb_ep0_task();
    irq_poll();
    extern void usb_bulk_out_task(void);
    usb_bulk_out_task();
    irq_poll();
    extern void usb_bulk_in_task(void);
    usb_bulk_in_task();
    irq_poll();
}

void
ctr_run_shutdownfuncs(void)
{
    extern void clear_active_irq(void);
    clear_active_irq();
    extern void usb_shutdown(void);
    usb_shutdown();
}

const struct initial_pin_s initial_pins[] PROGMEM = {
};
const int initial_pins_size PROGMEM = ARRAY_SIZE(initial_pins);

extern void DefaultHandler(void);
extern uint32_t _stack_end;
extern void ResetHandler(void);
extern void OTG_FS_IRQHandler(void);

const void *VectorTable[] __visible __section(".vector_table") = {
    &_stack_end,
    ResetHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    DefaultHandler,
    OTG_FS_IRQHandler,
};

uint32_t led_gpio = 0, led_gpio_high = 0; // "None"

int32_t button_gpio = 0, button_high = 0, button_pullup = 0; // ""
